#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Modify: Gary
# Blog: https://p3terx.com
#=================================================

name: gconf

on:
  watch:
    types: [started]
  #release:
  #  types: [published]
  #push:
  #  branches:
  #    - master
  #  paths:
  #    - '.config'
#  schedule:
#    - cron: 0 8 * * 5
 

env:
  #REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_URL:  https://github.com/lede-project/source
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: v19.07.1
  #REPO_BRANCH:  v17.01.7
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm /etc/apt/sources.list
        sudo cp sources.list  /etc/apt/sources.list
        sudo apt-get  update
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        curl -fsSL https://raw.githubusercontent.com/P3TERX/dotfiles/master/.bashrc >> ~/.bashrc


    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
      
    - name: overwrite
      run: |
        git clone --depth 1 https://github.com/robinZhao/Actions-OpenWrt.git overwrite
        \cp -rf overwrite/* openwrt/


    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
      
    - name: install driverfeeds
      run: |
        cd openwrt
        echo "src-git mtk https://github.com/Nossiac/mtk-openwrt-feeds;lede-17.01" >> feeds.conf.default
        scripts/feeds update -f mtk
        scripts/feeds install -a -p mtk

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'


    - name: Upload config
      uses: actions/upload-artifact@master
      with:
        name: config
        path: openwrt/config
